### PR TITLE
Update and rename drone.dart to car.py

### PR DESCRIPTION
**Pull request by proballstar**

### CODE REVIEW

**Comment by proballstar** [comment]
from @proballstar 

@aaronhma I have fixed it. It was a commenting err using // which is commenting in dart vs # which is commenting in python
For the print statement the indentation as fine but I had forgotten then end parenthesis
everyone makes mistakes and this was just one of the mistakes. 

Please commit and merge this PR and promote my access to at least Write

Thx,
@proballstar

**Comment by proballstar** [comment]
From @proballstar 

@aaronhma This is the model of the drone. When U runs this u can actually model the actions the drone can do and how to do it. 

We NEED this as u can put functions for each action and when u press each button on the drone, it then invokes the function.

**Comment by aaronhma** [comment]
@proballstar I'm closing this as on the drone, every piece of code hogs up RAM and CPU usage. This model doesn't even actually do anything that controls the drone! For that I'm closing this PR.

Best, Aaron

**Comment by proballstar** [comment]
I will edit with code from C++

**Pull request closed without merging**
